[package]
name = "gemed_test_database_installer"
version = "0.1.0"
edition = "2021"

[build]
target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.10"
bitness = "0.4.0"